spring.application.name=notification-service
server.port=8083

# AWS SQS
aws.sqs.queue-url=${SQS_QUEUE_URL:https://sqs.eu-central-1.amazonaws.com/123456789/order-created}

# Scheduling
spring.task.scheduling.pool.size=5